version: "3.8"
services:
  master:
    build: .
    container_name: spark-master
    command: bash -c "start-master.sh && tail -F /dev/null"
    ports:
      - "7077:7077"
      - "8080:8080"
    networks:
      - spark-net
  worker:
    build: .
    environment:
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1g
    command: bash -c "start-slave.sh spark://spark-master:7077 && tail -F /dev/null"
    networks:
      - spark-net
networks:
  spark-net:
    driver: bridge
